name: Example workflow for Python using Snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install Snyk CLI
        run: npm install -g snyk
      - name: Test Snyk Authentication
        run: |
          snyk auth ${{ secrets.SNYK_TOKEN }}
          snyk test --org=7d31ba38-a2ed-4b68-95af-83e7bc8a6f55
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          DEBUG: "*snyk*"
        with:
          args: --all-projects --org=7d31ba38-a2ed-4b68-95af-83e7bc8a6f55
